### ISSUE TITLE
UUIDs should be generated in the action creators instead of in the reducers

### ISSUE THREAD

**Issue by rgdelato** [survivejs-demos/redux-demo#1]
It's kind of a nitpicky thing, but when there are "impure" things in the reducers (such as random ID generation), it can break the devtool functionality (which is a big selling point of Redux). If you instead generate the IDs in the action creators and send the generated IDs as part of the action, then the IDs will still be consistent when you're doing things like undoing and replaying actions using the devtools.

**Comment by bebraw** [comment]
Thanks a lot! Fixed.
