### ISSUE TITLE
Firefox:the  notes state is one more than it should be.

### ISSUE THREAD

**Issue by lishoulong** [survivejs-demos/redux-demo#13]
When running my Kanban demo,I come across a problem, the nodes property of the state in the redux-devtools always come up to be one more than the actural ones.

For example,initial in the view page,there is only one "add button" which controls the adding of the lane, in this case, the state of the redux-devtools should be "lanes: [ ] 0 items; notes: [ ] 0 item",but it turn to be "lanes: [ ] 0 items; notes: [ ] 1 item";

I trire several ways "localStorage.clear();localStorage.debug = 1; localStorage.debug = 0;",clear the cache. But it return unchanged.

The version of my firefox is 45.0.2;in the chrome,all is ok.So should I pull-request at here or in the redux-devtools repository?

**Comment by bebraw** [comment]
Thanks for letting me know. This needs some further investigation. 👍

**Comment by bebraw** [comment]
I think I got one possible cause. If we remove a lane, it doesn't clean up associated notes. Those remain hanging in the store. I'll add some logic for that and we can give it a go again.

**Comment by lishoulong** [comment]
OK,looking for it.

**Comment by lishoulong** [comment]
Yeah,that`s it,I test deleting lane,the notes remain in the store.

**Comment by bebraw** [comment]
@lishoulong I added cleanup code there. Let me know how it goes.

**Comment by lishoulong** [comment]
OK,it is great . Both in Chrome and Firefox,now I delete lane,the notes in the store state accordingly decrease.
But when I flush the page ,in the Firefox,initially there are four notes in the store,I clear localstorage and session both  not work.So how i can initialize the store notes letting it synchronize with the view.

**Comment by bebraw** [comment]
> But when I flush the page ,in the Firefox,initially there are four notes in the store,I clear localstorage and session both not work.So how i can initialize the store notes letting it synchronize with the view.

Can you give me step by step instructions for this case? Assume `localStorage` is empty by default.

**Comment by lishoulong** [comment]
OK,It is in this case, as you know, the Reset button in the redux-devtools can reset the program.But when I reset it , the state in the store is odd, it is "lanes: [ ] 2 items; notes: [ ] 4 items". In the view, there are two lane,but no notes in each of the lane.

So that what I do such as add note,delete note, the state then change base on the four notes items.

**Comment by bebraw** [comment]
@lishoulong Can you describe how to get into a state like that? It's easier for me to see what might be causing the behavior (additional notes not associated to lanes).

**Comment by lishoulong** [comment]
Ok,just now I closed the localhost:8080 page, and clear the localstorage and session(in the Firefox),then I re-run the project . And I open the "localhost:8080" in a new opened page. It turned to be   that the state in the store is "lanes: [ ] 2 items; notes: [ ] 4 items", the view is "there are two lane,but no notes in each of the lane".
I hope the above can clarify the issue and the source.

**Comment by bebraw** [comment]
It sounds like it picked up data to `localStorage` _after_ you cleared it. Run

```
localStorage.clear()
localStorage.debug = 0
```

in console before refreshing. That latter line disabled the mechanism. If everything went right, the store should be completely empty. If so, use ´localStorage.debug = 1` to enable storing again.

I might have to figure out a neater way to deal with this as the flag isn't particularly nice.

**Comment by lishoulong** [comment]
OK, When I disable the mechanism, It works, the store is empty. And I enable the storing again,  it is ok. Thanks Beraw for your hot help.

**Comment by bebraw** [comment]
Cool to hear. Thanks. :+1:
