### ISSUE TITLE
Minimal Documentation Request

### ISSUE THREAD

**Issue by vjancik** [survivejs-demos/redux-demo#15]
I love that you ported the Kanban application into Redux. It's great to look at how the two solutions compare on the same project.

I think however, that the value of this project would go up a lot, if you added some minimal documentation on the Redux particularities.

Specifically, for me personally, the Redux DevTools are still somewhat obscure.

And even more specifically, could you explain (either in this issue, and / or subsequently in the README, and / or in the code) these:
https://github.com/survivejs-demos/redux-demo/blob/master/kanban_app/app/store/configureStore.dev.js#L8-L15
https://github.com/survivejs-demos/redux-demo/blob/master/kanban_app/app/store/configureStore.dev.js#L20-L26

I think people will appreciate! :)
Thank you.

**Comment by bebraw** [comment]
Good point. I'll get this done eventually.

The latter code is covered at http://survivejs.com/webpack/advanced-techniques/configuring-react/#configuring-redux .

On general level I'll be pushing all of my demos towards a certain structure. See the new [alt-demo](https://github.com/survivejs-demos/alt-demo). The connection between the React side and state management will be more controlled (goes through an adapter). This will allow us to swap between available solutions as we discuss them.

**Comment by bebraw** [comment]
Please open more issues for bits you would like to see documented. My apologies on the delay!
