### ISSUE TITLE
Implement a variant with Immutable.js

### ISSUE THREAD

**Issue by bebraw** [survivejs-demos/redux-demo#2]

**Comment by ngault** [comment]
+1.   I'd like to this

**Comment by bebraw** [comment]
There's an implementation below `immutable_demo` now. It might not be optimal in all ways and it could be possible to simplify it somehow. But it's a start.

Esp. immutable.js API might have some methods I'm not leveraging to the fullest extent yet. Some of the code might fold away through this.

**Comment by ngault** [comment]
Very nice.  I hope that you'll continue down this track, and I think that others would feel similarly.  Cheers.

**Comment by bebraw** [comment]
Sure. Let's see if I can get a little intermediate release out next week. :+1:
