### ISSUE TITLE
rewrite with babel6

### ISSUE THREAD

**Issue by Galen-Yip** [survivejs-demos/redux-demo#3]
ATT

**Comment by bebraw** [comment]
Yeah, I intend to do this soon. Thanks for the heads up. :+1:

**Comment by bebraw** [comment]
FYI, I have a working Babel 6 setup at https://github.com/survivejs/webpack_react . Just need to port that over and do some other tweaks while at it.

**Comment by Galen-Yip** [comment]
@bebraw thx guys.
