### ISSUE TITLE
Deleting a note causes an error

### ISSUE THREAD

**Issue by joseph-abell** [survivejs-demos/redux-demo#4]
![image](https://cloud.githubusercontent.com/assets/1398893/12377723/24164116-bd1f-11e5-9615-795e8f73e30e.png)

**Comment by joseph-abell** [comment]
So I tried to delete the only note, and it cannot read the id, and the note still exists

**Comment by bebraw** [comment]
Thanks!

I made the `Lanes` rendering logic more robust to take this case into account.

I have a better fix in mind, but I'll get back to that later after I've thought it through.
