### ISSUE TITLE
clicking away from the lane without changing it's name deletes the lane.

### ISSUE THREAD

**Issue by joseph-abell** [survivejs-demos/redux-demo#5]
![image](https://cloud.githubusercontent.com/assets/1398893/12378825/58ab9890-bd42-11e5-84a9-56030215d727.png)
I created a lane.

![image](https://cloud.githubusercontent.com/assets/1398893/12378827/79a02458-bd42-11e5-9c3a-556b6787c2a1.png)
click the title to change the name of the lane

![image](https://cloud.githubusercontent.com/assets/1398893/12378832/a8bc1fbc-bd42-11e5-867f-51972acfcb83.png)
I clicked away from the lane. As you can see the lane has been deleted.

![image](https://cloud.githubusercontent.com/assets/1398893/12378838/c4579300-bd42-11e5-952b-e433404d714e.png)

**Comment by bebraw** [comment]
Yeah, this is due to the deletion logic in place. It's by design. Empty field should trigger delete. Maybe not the best option, though. Any ideas?

**Comment by joseph-abell** [comment]
It would be good to have the delete button for lanes to follow the same logic and placement as the notes. hovering over the lane would bring up a delete button. Of course this would mean the + button would need to move, maybe underneath the title, as a subtitle.

Alternatively, or maybe both, make the delete button bring a popup or similar, making sure the user wishes to delete it.

**Comment by bebraw** [comment]
Ok, I'll think about this. Hovering would be nice, yeah. Maybe "+" could live on left.

**Comment by bebraw** [comment]
This has to do with the `onBlur` behavior. I think I'll convert the input to controlled one so that it gets the initial value and then maintains it internally. This way `onBlur` is fine and UX is a little better.
