### ISSUE TITLE
Naming the lane with only a space makes it impossible to rename the lane again.

### ISSUE THREAD

**Issue by joseph-abell** [survivejs-demos/redux-demo#6]
![image](https://cloud.githubusercontent.com/assets/1398893/12378852/fa0660a8-bd42-11e5-83fa-3e136ae7fc08.png)
I've added a single space into the lane name.

![image](https://cloud.githubusercontent.com/assets/1398893/12378855/0fddca92-bd43-11e5-8818-de81a1da4ccb.png)
This successfully renames the lane, and as it is a space, there is nothing to click to rename it to something more useful.

**Comment by bebraw** [comment]
That's an interesting corner case. It obviously works with regular text but space isn't certain that. This might need a little CSS fix. Ideas are welcome.

**Comment by joseph-abell** [comment]
trim the result before attempting to submit it? but then you would accidentally delete the lane, in that case.

**Comment by bebraw** [comment]
Trimming sounds like a great idea. Easy to implement. :+1:

**Comment by bebraw** [comment]
I ended up pushing the logic to a separate user interface control (same idea as for individual notes). That seemed like the neatest thing to do.
