### ISSUE TITLE
add redux-devtools package

### ISSUE THREAD

**Issue by Galen-Yip** [survivejs-demos/redux-demo#7]
I am looking forward.

**Comment by Galen-Yip** [comment]
thank you guy

**Comment by bebraw** [comment]
No probs. Let me know if there are any issues.

I think I'll do a few tweaks to the Kanban to make the implementation a little nicer.

**Comment by Galen-Yip** [comment]
yeah~ good news
i think it can add react-router too 
there are too many repos focus on one character，you can combine them

**Comment by bebraw** [comment]
What do you think of [redux-simple-router](https://github.com/rackt/redux-simple-router)? So far I've been watching the development from sidelines.

**Comment by Galen-Yip** [comment]
yep~i am testing a repo of redux with react-router , but encounter a trouble，i wanna replace it with redux-simple-router later.
woule u mind taking a look?

**Comment by bebraw** [comment]
@Galen-Yip Link me to your repo and let me know of the error. :)

**Comment by Galen-Yip** [comment]
oh sorrrrrry.. i 've just left for a while
[https://github.com/Galen-Yip/react-redux-router](https://github.com/Galen-Yip/react-redux-router)

when in `npm start`， `Uncaught TypeError: Cannot read property 'toArray' of undefined` error show

**Comment by Galen-Yip** [comment]
i think that the component can't get the `props` due to react-router, right?

**Comment by bebraw** [comment]
@Galen-Yip It happens because `this.props.items` is `undefined`. Here's a patch against that:

``` javascript
diff --git a/app/components/Content.jsx b/app/components/Content.jsx
index b4b640d..1f12d59 100644
--- a/app/components/Content.jsx
+++ b/app/components/Content.jsx
@@ -8,11 +8,11 @@ import classNames from 'classnames';
 class Content extends React.Component {
     render() {
         console.log('-------' + JSON.stringify(this.props))
-        const items = this.props.items.toArray();
+        const items = this.props.items ? this.props.items.toArray() : [];

         return(
             <ul>
-                {item.map(v => 
+                {items.map(v => 
                     <ListItem 
                         key={v} 
                         item={v}
diff --git a/app/containers/home.jsx b/app/containers/home.jsx
index 8807cfc..5ca9cc2 100644
--- a/app/containers/home.jsx
+++ b/app/containers/home.jsx
@@ -14,7 +14,7 @@ class Home extends React.Component {
     static propTypes = {
         items: React.PropTypes.object,
         filter: React.PropTypes.string
-    }
+    };

     render() {
         const styles = {
@@ -41,4 +41,4 @@ export default connect(
     dispatch => ({
         actions: bindActionCreators(ItemActions, dispatch)
     })
-)(Home)
\ No newline at end of file
+)(Home)
diff --git a/package.json b/package.json
index 7b069af..19a48a3 100644
--- a/package.json
+++ b/package.json
@@ -44,10 +44,12 @@
   "dependencies": {
     "classnames": "^2.2.3",
     "history": "^1.17.0",
+    "immutable": "^3.7.6",
     "lodash": "^4.0.0",
     "node-uuid": "^1.4.7",
     "react": "^0.14.5",
     "react-dom": "^0.14.5",
+    "react-immutable-render-mixin": "^0.9.2",
     "react-redux": "^4.0.6",
     "react-router": "^1.0.3",
     "redux": "^3.0.5",
```

You could also deal with it using `propTypes`. That would be far neater. This was just a quick hack to get the app to work.

**Comment by Galen-Yip** [comment]
yes , `this.props` is `undefined`,
 But i set `const initialItems = Immutable.List([1,2,3]);` in reducers/home.js .
it seemed that props is not  set

**Comment by bebraw** [comment]
@Galen-Yip Did you try applying my patch (`git apply`)?

**Comment by Galen-Yip** [comment]
sure guy ~
i have push the new to repo

**Comment by Galen-Yip** [comment]
@bebraw i made a stupid mistake - -.... the problem comes resolved

**Comment by bebraw** [comment]
@Galen-Yip Ok, cool. What was the problem in the end?

**Comment by bebraw** [comment]
@Galen-Yip Ah, import at `import items from './items';`. Got it. :+1:

**Comment by Galen-Yip** [comment]
@bebraw yes ...T T thx for your help bro

**Comment by Galen-Yip** [comment]
oooh what do you think of this view?
[http://staltz.com/why-react-redux-is-an-inferior-paradigm.html](http://staltz.com/why-react-redux-is-an-inferior-paradigm.html)

**Comment by bebraw** [comment]
@Galen-Yip Feel free to join me at [gitter](https://gitter.im/survivejs/webpack_react). We can continue there.

It's an interesting post with some good points. We're still figuring things out so tech is bound to change. That said, there's no absolute need to be on the bleeding edge always. It's bleeding for a reason. Sometimes it's enough to just get things done and adopt the tech as it's more stable.
